import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Main from '../components/Main'
import { PaystackButton } from 'react-paystack'


export default function Home() {
  const publicKey = process.env.NEXT_PUBLIC_publicKey;
  console.log(publicKey);
  const amount = 100000

 

  const[email, setEmail] = useState("");
  const[firstName, setFirstName] = useState("");
  const[lastName, setLastName] = useState("");
  console.log(firstName);
  // const[phone, setPhone] = useState("");
  const ComponentProps ={
    email,
    amount,
    metadata: {
      firstName,
      lastName,
    },
    publicKey,
    text: "Pay Now",
    onSuccess: () => alert("success!"),
    onClose: () => alert("Wait"),
  }
  return (
    <div >
      <Head>
        <title>theEnthusiastAcademy | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header  className={`xl:px-10 xl:py-5 xl:bg-purple-800`} > 
      </Header>

      <Main 
        setEmail={setEmail}
        setFirstName={setFirstName}
        setLastName={setLastName}
        PaystackButton={PaystackButton}
        ComponentProps={ComponentProps}
      ></Main>

      
      <Footer
        className={`xl:footer xl:p-10 xl:bg-neutral xl:text-neutral-content`}>
      </Footer>
    </div>
  )
}


